name: Pipeline for Continuous Integration and Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  audit-job:
    name: Audit Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Audit production dependencies
        run: npm audit --omit=dev

  build-job:
    name: Build Artifact
    runs-on: ubuntu-latest
    needs: audit-job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Move build to root
        run: |
          rm -rf public
          mv build public
      - name: Upload Pages Artifact
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public

  lint-job:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Fix permissions
        run: chmod +x node_modules/.bin/eslint
      - name: Lint code
        run: npm run lint

  test-job:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint-job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Fix permissions
        run: chmod +x node_modules/.bin/jest
      - name: Run tests
        run: npm run test-ci

  static-analysis-job:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    needs: test-job
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run static analysis
        run: npm run lint

  smoke-test-job:
    name: Smoke Test
    runs-on: ubuntu-latest
    needs: static-analysis-job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run smoke test
        run: npm run smoke

  deploy-pages-job:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: [build-job, test-job, static-analysis-job, smoke-test-job]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

