name: Pipeline for Continuous Integration and Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit-job:
    name: Audit Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit production dependencies
        run: npm audit --omit=dev 

  build-job: 
    name: Build Artifact
    runs-on: ubuntu-latest
    needs: audit-job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  lint-job:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint

  test-job:
    name: Run Tests
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test-ci

  static-analysis-job:
    name: Static Code Analysis
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/codeql-action/init@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Run static analysis
        run: npm run static-analysis

  deploy-job:
    name: Deploy Artifact
    runs-on: ubuntu-latest
    needs:
      - lint-job
      - test-job
      - static-analysis-job
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build

  verify-job:
    name: Verify Deployment
    needs:
      - deploy-job
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Run smoke test
        run: |
          export TEST_URL=<URL_TO_TEST>
          npm install
          npm run smoke
